### ISSUE TITLE
Only Support for ES6?

### ISSUE THREAD

**Issue by splifo** [ghaiklor/sails-service-mailer#44]
Hello, 
Thank you for this tool.

There is a way to load this tool without using es6?

Sorry for my English.

Thx

<b>Upd: </b> after updating node to v5.4.1 i got the error : unexpected token import.
(api/services/MailerService.js)

**Comment by splifo** [comment]
My solution was to install babel. Hope this is not the best. if you have other one this could be helpfull. 
Otherwise need to add Babl dependencie in the doc. thx and waiting .... :)

**Comment by splifo** [comment]
Now i got the error : MailerService.send is not a function. Thank you for help

**Comment by splifo** [comment]
up!

**Comment by ghaiklor** [comment]
@splifo it compiles to compatible NodeJS 4.x and higher. If you have installed it from npm you should be able to use it.
